# Generated by Django 2.0.7 on 2018-07-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Altura em cm'),
            preserve_default=False,
        ),
    ]
