# Generated by Django 2.0.7 on 2018-07-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_myuser_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura em cm'),
        ),
    ]
