# Generated by Django 2.0.7 on 2018-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180705_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='Peso em kg'),
            preserve_default=False,
        ),
    ]
