# Generated by Django 2.0.7 on 2018-07-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myuser_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='imc',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='IMC - Indice de massa corporal'),
            preserve_default=False,
        ),
    ]
