# Generated by Django 2.0.7 on 2018-07-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_myuser_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='genero',
            field=models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='myuser',
            name='idade',
            field=models.IntegerField(default=1, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='nascimento',
            field=models.CharField(default=1, max_length=10, verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
    ]
