# Generated by Django 2.0.7 on 2018-07-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180705_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='genero',
            field=models.CharField(choices=[('1', 'Selecione'), ('2', 'Masculino'), ('3', 'Feminino')], default='1', max_length=3),
        ),
    ]
