# Generated by Django 2.0.7 on 2018-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_exercicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['exercicio'], 'verbose_name': 'Exercicio', 'verbose_name_plural': 'Exercicios'},
        ),
        migrations.AddField(
            model_name='exercicio',
            name='musculo',
            field=models.CharField(choices=[('1', 'Abdome'), ('2', 'Bíceps'), ('3', 'Costas'), ('4', 'Peito'), ('5', 'Pernas'), ('6', 'Tríceps'), ('7', 'Ombros'), ('8', 'Nádegas')], default='1', max_length=8),
        ),
    ]
